---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: mcpgateways.jetski.sh
spec:
  group: jetski.sh
  names:
    kind: MCPGateway
    listKind: MCPGatewayList
    plural: mcpgateways
    shortNames:
    - mcpg
    singular: mcpgateway
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: MCPGateway is the Schema for the mcpgateways API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: MCPGatewaySpec defines the desired state of MCPGateway
            properties:
              authorization:
                properties:
                  dynamicClientRegistration:
                    properties:
                      publicClient:
                        type: boolean
                    type: object
                type: object
              customDomain:
                type: string
              organizationId:
                type: string
              organizationName:
                type: string
              projects:
                items:
                  properties:
                    authenticationEnabled:
                      type: boolean
                    deploymentRevisionId:
                      type: string
                    projectId:
                      type: string
                    projectName:
                      type: string
                    proxyUrl:
                      type: string
                    telemetryEnabled:
                      type: boolean
                  required:
                  - authenticationEnabled
                  - deploymentRevisionId
                  - projectId
                  - projectName
                  - telemetryEnabled
                  type: object
                type: array
            required:
            - organizationId
            - organizationName
            type: object
          status:
            description: MCPGatewayStatus defines the observed state of MCPGateway
            type: object
        required:
        - metadata
        type: object
    served: true
    storage: true
    subresources:
      status: {}
