services:
  dex:
    image: ghcr.io/hyprmcp/dex:2.44.0-alpine
    command: ["dex", "serve", "/config.yaml"]
    ports:
      - "127.0.0.1:5556:5556"
      - "127.0.0.1:5557:5557"
    configs:
      - source: config.yaml
        target: /config.yaml
    env_file:
      - .dex.secret.env

  postgres:
    image: "postgres:17.5-alpine3.20"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: jetski
    volumes:
      - "postgres:/var/lib/postgresql/data/"
    ports:
      - "127.0.0.1:5432:5432"

  mailpit:
    image: "axllent/mailpit:v1.27.10"
    ports:
      - "1025:1025"
      - "8025:8025"

configs:
  config.yaml:
    content: |
      issuer: http://host.minikube.internal:5556
      web:
        http: 0.0.0.0:5556
        allowedOrigins: ['*']
      grpc:
        addr: 0.0.0.0:5557
      storage:
        type: sqlite3
      oauth2:
        skipApprovalScreen: true
      staticClients:
        - id: ui
          name: 'Jetski Development'
          public: true
          redirectURIs:
          - 'http://localhost:4200'
          - 'http://localhost:8080'
        - id: cli
          name: 'Jetski CLI'
          public: true
          redirectURIs:
          - '/device/callback'
      enablePasswordDB: true
      staticPasswords:
        - email: "admin@example.com"
          # bcrypt hash of the string "password" for user admin: $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
          hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
          username: "admin"
          userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
        - email: "pmig@glasskube.com"
          hash: "$2a$10$.t87twHmZDYCBSPxfnxfWu4tsS/6XfYFZ0El0ppBl2DeTgXqJ53/6"
          username: "pmig"
          userID: "576e6e3f-89f6-4821-abbb-7da2a22f9e38"
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: {{ .Env.GITHUB_CLIENT_ID }}
          clientSecret: {{ .Env.GITHUB_CLIENT_SECRET }}
          redirectURI: http://localhost:5556/callback
      expiry:
        idTokens: "5m"

volumes:
  postgres:
